# Revised case normalization for Hirslanden Beausite 2018

Notes:

- 17 of 17 revised DtoD cases were joined with the BFS cases from the DB.

In [1]:
import sys
sys.path.insert(0, '/home/jovyan/work')

from src.revised_case_normalization.notebook_functions.global_configs import *
from src.revised_case_normalization.notebook_functions.normalize import normalize
from src.revised_case_normalization.notebook_functions.revise import revise
from src.revised_case_normalization.notebook_functions.group import group
from src.revised_case_normalization.notebook_functions.update_db import update_db

In [2]:
file_info = FileInfo(os.path.join(ROOT_DIR, 'raw_data/HI-Bern_Salem_Beau Site_Linde.xlsx'),
                     'Hirslanden Beau Site', '2018', 'Änderungen Beau Site_ 2018')

print(file_info)

FileInfo(path='/home/jovyan/work/src/revised_case_normalization/raw_data/HI-Bern_Salem_Beau Site_Linde.xlsx', hospital_name_db='Hirslanden Beau Site', year='2018', sheet='Änderungen Beau Site_ 2018')

In [3]:
revised_cases_df = normalize(file_info)
revised_cases_df

2022-11-10 10:17:05.276 | INFO     | src.revised_case_normalization.notebook_functions.normalize:normalize:35 - Read 26 cases for Hirslanden Beau Site 2018
2022-11-10 10:17:05.280 | INFO     | src.revised_case_normalization.notebook_functions.normalize:normalize:59 - TYPES:
datum                             string
tranche                           string
case_id                           object
patient_id                        object
gender                            string
age_years                          int64
bfs_code                          string
duration_of_stay                   int64
pflegetage neu                    string
pccl                               int64
pccl neu                          string
old_pd                            string
primary_diagnosis                 string
added_icds                        string
removed_icds                      string
added_chops                       string
removed_chops                     string
drg                               string
drg neu                           string
cw alt                            string
cw neu                            string
cw-änderung möglich               string
cw änderung akzeptiert            string
unnamed: 23                       string
kommentar dtod                    string
kommentar kodierung hirslanden    string
ablehnung arzt/ kasse             string
case_id_norm                      object
dtype: object
2022-11-10 10:17:05.287 | INFO     | src.utils.dataframe_utils:validate_icd_codes:68 - Validated ICD codes in 'added_icds' and stored them into 'added_icds': All rows contain valid codes
2022-11-10 10:17:05.291 | INFO     | src.utils.dataframe_utils:validate_icd_codes:68 - Validated ICD codes in 'removed_icds' and stored them into 'removed_icds': All rows contain valid codes
2022-11-10 10:17:05.295 | INFO     | src.utils.dataframe_utils:validate_chop_codes:106 - Validated CHOP codes in 'added_chops' and stored them into 'added_chops': All rows contain valid codes
2022-11-10 10:17:05.298 | INFO     | src.utils.dataframe_utils:validate_chop_codes:106 - Validated CHOP codes in 'removed_chops' and stored them into 'removed_chops': All rows contain valid codes
2022-11-10 10:17:05.298 | INFO     | src.utils.dataframe_utils:remove_duplicated_chops:32 - Removing duplicated CHOP codes due to different casing ...
2022-11-10 10:17:05.303 | INFO     | src.utils.dataframe_utils:validate_pd_revised_sd:161 - Validated redundant PD info in 'added_icds'/'removed_icds': The following 1 rows were affected:
row 24: primary diagnosis I5001 => I5019
2022-11-10 10:17:05.306 | SUCCESS  | src.revised_case_normalization.notebook_functions.normalize:normalize:106 - Completed validation

       case_id  patient_id gender  age_years  duration_of_stay case_id_norm old_pd primary_diagnosis bfs_code  pccl   drg                 added_icds removed_icds                     added_chops removed_chops
0   0041635636  0005050208      W         83                 5     41635636  J4419             J4419     M100     3  E65C                     [B965]           []                              []            []
1   0041647892  0005087263      W         74                11     41647892   I350              I350     M200     3  F03D                     [I490]           []                          [9962]            []
2   0041656218  0022162393      M         77                11     41656218   I350              I350     M200     3  F03D                [J61, D689]           []                              []            []
3   0041660312  0005287267      W         54                30     41660312  K5722             K5722     M200     3  G02C                      [E43]        [E46]                              []            []
4   0041670261  0005121840      M         90                 6     41670261   I480              I480     M100     3  F71B                     [N183]       [N184]                              []            []
5   0041622665  0022168673      M         79                12     41622665    C20               C20     M200     3  G17Z                     [N133]           []                              []            []
6   0041631826  0022164652      M         59                11     41631826   I208              I208     M200     3  F06D                [D62, I490]       [D508]                          [9962]            []
7   0041632678  0005001742      W         58                 5     41632678   K316              K316     M200     3  G18B                    [E6692]      [E6691]                              []            []
8   0041642176  0001033482      M         82                10     41642176  I7024             I7024     M100     3  F13C               [I650, I652]           []                              []            []
9   0041670429  0011088007      W         73                 4     41670429   I214              I214     M100     2  F60B  [I5001, N183, I452, I361]           []                              []            []
10  0041678445  0022176834      M         73                32     41678445   K566              K566     M200     3  G02C                     [E440]        [E46]                              []            []
11  0041796989  0005078697      M         49                22     41796989   C187              C187     M200     3  G18B              [K9183, K650]           []  [459812, 461212, 5413, 389311]            []
12  0041718006  0001148792      W         77                17     41718006   C252              C252     M200     3  H09B                    [E1390]           []                              []            []
13  0041727313  0022184206      M         67                11     41727313   K704              K704     M100     3  H60C                     [I982]           []                              []            []
14  0041740292  0022186059      W         86                 9     41740292   K449              K449     M200     3  G19B                      [E43]           []                              []            []
15  0041755915  0001065168      W         81                 3     41755915  K5731             K5731     M100     2  G46C               [B022, G530]           []                              []            []
16  0041762114  0005047937      W         72                17     41762114  K9188             K9188     M200     3  G48C                      [E43]           []                              []            []
17  0041766569  0005090762      W         71                12     41766569  I5001             I5001     M100     3  F62C                    [J9619]           []                              []            []
18  0041767906  0005256414      M         43                10     41767906  K5722             K5722     M200     3  G18A                     [K659]           []                              []            []
19  0041778442  0022187255      W         71                12     41778442  I2513             I2513     M200     3  F06D                      [D62]           []                              []            []
20  0041781983  0005070312      W         74                 6     41781983   K914              K914     M200     3  G18B                      [E43]           []                              []            []
21  0041830088  0022197396      M         63                11     41830088   C187              C187     M200     3  G18B                     [K566]           []                              []            []
22  0041861755  0005180098      W         86                 1     41861755  E1160             E1160     M100     2  K60F                    [G2090]           []                              []            []
23  0041863191  0005147943      W         85                 3     41863191   D376              D376     M200     3  H61B         [N183, K767, D684]       [N185]                              []            []
24  0041869562  0022192074      W         95                 9     41869562  I5001             I5019     M100     3  F62C                         []           []                              []            []
25  0041897876  0011072389      M         63                 6     41897876   K922              K922     M100     3  G48C                      [D62]           []                        [990410]            []

# Match revised DtoD data with the BfS data from the database

In [4]:
cols_to_join = list(VALIDATION_COLS)
cols_to_join.remove(CASE_ID_COL)
cols_to_join.append(NORM_CASE_ID_COL)
# Ignore the patient ID in this dataset, because it is encrypted
cols_to_join.remove(PATIENT_ID_COL)

revised_cases, unmatched = revise(file_info, revised_cases_df, validation_cols=cols_to_join)
revised_cases.head()

2022-11-10 10:17:06.690 | INFO     | src.service.bfs_cases_db_service:get_sociodemographics_for_hospital_year:90 - Read 6319 rows from the DB, for the hospital 'Hirslanden Beau Site' in 2018

   aimedic_id     case_id primary_diagnosis                     secondary_diagnoses  primary_procedure                                                                           secondary_procedures gender  age_years  age_days  gestation_age  duration_of_stay  ventilation_hours grouper_admission_type admission_date  admission_weight grouper_discharge_type discharge_date
0      125653  0041642176             I7024   [M8687, B957, B9590, T810, Y849, ...]  381811:R:20180113         [992218::20180112, 0040:R:20180113, 8411:R:20180113, 990A::20180113, 99B711::20180113]      M         82         0              0                10                  0                     11     2018-01-12                 0                     00     2018-01-22
1      125852  0041656218              I350    [I2513, I1090, E788, C61, C795, ...]   35F121::20180201  [361122::20180201, 361126::20180201, 361C12::20180201, 396111::20180201, 3963::20180201, ...]      M         77         0              0                11                 24                     01     2018-01-31                 0                     00     2018-02-11
2      125867  0041670429              I214  [I2511, Z950, I1090, E780, E1190, ...]     8954::20180203                                                                                             []      W         73         0              0                 4                  0                     01     2018-02-03                 0                     00     2018-02-07
3      126121  0041767906             K5722     [K668, K9188, D62, T810, I958, ...]   457611::20180517  [009A13::20180517, 009A11::20180517, 4596::20180517, 880110::20180517, 990410::20180517, ...]      M         43         0              0                10                  0                     01     2018-05-17                 0                     00     2018-05-27
4      126806  0041718006              C252    [K590, Z888, F134, I1090, E789, ...]   525211::20180403       [415::20180403, 403X29:B:20180403, 009B11::20180403, 99B711::20180403, 890A32::20180405]      W         77         0              0                17                  0                     01     2018-04-02                 0                     00     2018-04-19

In [5]:
if unmatched.shape[0] > 0:
    unmatched

In [6]:
revisions_update, diagnoses_update, procedures_update = group(revised_cases)
revisions_update[REVISION_DATE_COL] = '2022-12-31'

2022-11-10 10:17:07.136 | INFO     | src.revised_case_normalization.notebook_functions.group:group:83 - Grouping 26 cases ...
2022-11-10 10:17:08.197 | SUCCESS  | src.revised_case_normalization.notebook_functions.group:group:88 - Grouped 26 cases into: 26 revisions, 315 diagnoses rows, 178 procedure rows

In [7]:
revisions_update

    aimedic_id   drg  drg_cost_weight  effective_cost_weight  pccl revision_date
0       125653  F59B             2.55                   2.55     4    2022-12-31
1       125852  F03C             4.90                   4.90     4    2022-12-31
2       125867  F60A             1.45                   1.45     4    2022-12-31
3       126121  G02A             4.32                   4.32     4    2022-12-31
4       126806  H09A             3.02                   3.02     4    2022-12-31
5       127173  G18A             2.96                   2.96     4    2022-12-31
6       127217  G64A             1.51                   1.51     4    2022-12-31
7       127473  F03C             4.90                   4.90     4    2022-12-31
8       127526  G48C             0.99                   0.99     3    2022-12-31
9       127695  F62B             1.30                   1.30     4    2022-12-31
10      127794  F62B             1.30                   1.30     4    2022-12-31
11      128560  H60B             1.76                   1.76     4    2022-12-31
12      128616  G02A             4.32                   4.32     4    2022-12-31
13      129157  G19A             2.71                   2.71     4    2022-12-31
14      129571  F06C             3.84                   3.84     4    2022-12-31
15      129701  G18A             2.96                   2.96     4    2022-12-31
16      129830  F71A             1.12                   1.12     4    2022-12-31
17      130020  E65A             1.08                   1.08     4    2022-12-31
18      130064  H61A             1.35                   1.03     4    2022-12-31
19      130431  G02A             4.32                   4.32     4    2022-12-31
20      130541  G04B             3.49                   3.49     4    2022-12-31
21      130943  G19A             2.71                   2.71     4    2022-12-31
22      131112  G46B             1.49                   1.49     4    2022-12-31
23      131674  G13Z             4.10                   3.64     4    2022-12-31
24      131724  K60D             0.96                   0.34     3    2022-12-31
25      131838  F06C             3.84                   3.84     4    2022-12-31

In [8]:
update_db(revisions_update, diagnoses_update, procedures_update)

2022-11-10 10:17:08.216 | INFO     | src.service.bfs_cases_db_service:insert_revised_cases_into_revisions:249 - Trying to insert 26 cases into the 'Revisions' table ...
2022-11-10 10:17:14.354 | INFO     | src.service.bfs_cases_db_service:insert_revised_cases_into_revisions:275 - Deleted 26 rows from the "Revisions" table, which is about to be updated
2022-11-10 10:17:14.402 | SUCCESS  | src.service.bfs_cases_db_service:insert_revised_cases_into_revisions:286 - Inserted 26 cases into the 'Revisions' table
2022-11-10 10:17:14.404 | INFO     | src.service.bfs_cases_db_service:insert_revised_cases_into_diagnoses:298 - Trying to insert 315 rows into the 'Diagnoses' table ...
2022-11-10 10:17:15.977 | SUCCESS  | src.service.bfs_cases_db_service:insert_revised_cases_into_diagnoses:336 - Inserted 315 rows into the 'Diagnoses' table
2022-11-10 10:17:15.979 | INFO     | src.service.bfs_cases_db_service:insert_revised_cases_into_procedures:347 - Trying to insert 178 rows into the 'Procedures' table ...
2022-11-10 10:17:16.963 | SUCCESS  | src.service.bfs_cases_db_service:insert_revised_cases_into_procedures:393 - Inserted 178 rows into the 'Procedures' table