# Revised case normalization for Hirslanden Zürich 2017

Notes:

- 17 of 17 revised DtoD cases were joined with the BFS cases from the DB.

In [1]:
import sys
sys.path.insert(0, '/home/jovyan/work')

from src.revised_case_normalization.notebook_functions.global_configs import *
from src.revised_case_normalization.notebook_functions.normalize import normalize
from src.revised_case_normalization.notebook_functions.revise import revise
from src.revised_case_normalization.notebook_functions.group import group
from src.revised_case_normalization.notebook_functions.update_db import update_db

In [2]:
file_info = FileInfo(os.path.join(ROOT_DIR, 'raw_data/HI-Zurich.xlsx'),
                     'Hirslanden Zurich', '2017', 'Änderungen_Hirslanden_2017')

print(file_info)

FileInfo(path='/home/jovyan/work/src/revised_case_normalization/raw_data/HI-Zurich.xlsx', hospital_name_db='Hirslanden Zurich', year='2017', sheet='Änderungen_Hirslanden_2017')

In [3]:
revised_cases_df = normalize(file_info)
revised_cases_df

2022-11-09 16:05:53.841 | INFO     | src.revised_case_normalization.notebook_functions.normalize:normalize:35 - Read 128 cases for Hirslanden Zurich 2017
2022-11-09 16:05:53.846 | INFO     | src.revised_case_normalization.notebook_functions.normalize:normalize:59 - TYPES:
datum                                                string
tranche                                              string
case_id                                              object
patient_id                                           object
gender                                               string
age_years                                             int64
bfs_code                                             string
duration_of_stay                                      int64
pflegetage neu                                       string
pccl                                                  int64
pccl neu                                             string
old_pd                                               string
primary_diagnosis                                    string
added_icds                                           string
removed_icds                                         string
added_chops                                          string
removed_chops                                        string
drg                                                  string
drg neu                                              string
cw alt                                               string
cw neu                                               string
cw-änderung                                          string
cw änderung akzeptiert                               string
kommentar dtod                                       string
kodierer                                             string
kommentar kodierung hirslanden                       string
dtod gegenargumentation zu rückmeldung hirslanden    string
ablehnung kasse                                      string
case_id_norm                                         object
dtype: object
2022-11-09 16:05:53.857 | INFO     | src.utils.dataframe_utils:validate_icd_codes:68 - Validated ICD codes in 'added_icds' and stored them into 'added_icds': All rows contain valid codes
2022-11-09 16:05:53.864 | INFO     | src.utils.dataframe_utils:validate_icd_codes:68 - Validated ICD codes in 'removed_icds' and stored them into 'removed_icds': All rows contain valid codes
2022-11-09 16:05:53.870 | INFO     | src.utils.dataframe_utils:validate_chop_codes:106 - Validated CHOP codes in 'added_chops' and stored them into 'added_chops': All rows contain valid codes
2022-11-09 16:05:53.912 | INFO     | src.utils.dataframe_utils:validate_chop_codes:106 - Validated CHOP codes in 'removed_chops' and stored them into 'removed_chops': All rows contain valid codes
2022-11-09 16:05:53.913 | INFO     | src.utils.dataframe_utils:remove_duplicated_chops:32 - Removing duplicated CHOP codes due to different casing ...
2022-11-09 16:05:53.924 | INFO     | src.utils.dataframe_utils:validate_pd_revised_sd:161 - Validated redundant PD info in 'added_icds'/'removed_icds': The following 2 rows were affected:
row 106: primary diagnosis J181 => J4400
row 126: primary diagnosis J4481 => J4480
2022-11-09 16:05:53.927 | INFO     | src.revised_case_normalization.notebook_functions.normalize:normalize:104 - Removed 2 rows containing duplicates
2022-11-09 16:05:53.927 | SUCCESS  | src.revised_case_normalization.notebook_functions.normalize:normalize:106 - Completed validation

      case_id        patient_id gender  age_years  duration_of_stay case_id_norm old_pd primary_diagnosis bfs_code  pccl   drg   added_icds removed_icds added_chops removed_chops
0    41230054  E8CD6759509644DE      M         78                11     41230054   C341              C341     M200     3  E06C       [J939]           []          []            []
1    41194118  41309F148FEDBFD2      W         39                 7     41194118   O335              O335     M300     3  O01E       [K560]           []          []            []
2    41230059  7E79B28620A3A8E3      M         84                 8     41230059    C61               C61     M200     3  M09B       [C795]           []          []            []
3    41231720  FBB0408939EC3E8B      M         81                 6     41231720  J4402             J4402     M100     3  E65C      [E1191]      [E1190]          []            []
4    41243610  32E2ED09CA696444      W         82                 7     41243610  J4412             J4412     M100     3  E65C        [J81]           []          []            []
..        ...               ...    ...        ...               ...          ...    ...               ...      ...   ...   ...          ...          ...         ...           ...
123  41249123  9F60C5E2FF49ADFA      M         72                 9     41249123   C671              C671     M200     2  L18B       [U804]           []          []            []
124  41323252  473038E4266105E6      W         80                 8     41323252   N390              N390     M100     3  L06B       [U804]           []          []            []
125  41340499  38988935DC3B2582      M         57                 7     41340499    N10               N10     M100     3  L63D       [U804]        [U81]          []            []
126  41347960  4CA999AAFA0018CC      W         76                 3     41347960  J4481             J4480     M100     0  E65C           []           []          []            []
127  41385331  5BF999E843E86BDE      W         92                17     41385331  I5001             I5001     M100     2  F62C  [E43, I361]           []          []            []

[126 rows x 15 columns]

# Match revised DtoD data with the BfS data from the database

In [4]:
cols_to_join = list(VALIDATION_COLS)
cols_to_join.remove(CASE_ID_COL)
cols_to_join.append(NORM_CASE_ID_COL)
# Ignore the patient ID in this dataset, because it is encrypted
cols_to_join.remove(PATIENT_ID_COL)

revised_cases, unmatched = revise(file_info, revised_cases_df, validation_cols=cols_to_join)
revised_cases.head()

2022-11-09 16:05:55.192 | INFO     | src.service.bfs_cases_db_service:get_sociodemographics_for_hospital_year:90 - Read 19047 rows from the DB, for the hospital 'Hirslanden Zurich' in 2017

   aimedic_id   case_id primary_diagnosis                      secondary_diagnoses primary_procedure                                                                                secondary_procedures gender  age_years  age_days  gestation_age  duration_of_stay  ventilation_hours grouper_admission_type admission_date  admission_weight grouper_discharge_type discharge_date
0       45537  41418386             M4806  [G553, M4785, I1091, I7021, J4482, ...]    8108::20170704     [816220::20170704, 785035::20170704, 805110::20170704, 845110::20170704, 784987::20170704, ...]      W         79         0              0                16                  0                     01     2017-07-03                 0                     00     2017-07-19
1       45602  41243205              N390                [M9326, G301, F001, R470]  992212::20170109                                                                                  [948X40::20170109]      W         80         0              0                10                  0                     01     2017-01-09                 0                     00     2017-01-19
2       45634  41486629              I714     [T828, Y828, I1090, E780, T818, ...]  397114::20170831  [39783G::20170831, 399110:B:20170831, 884211::20170831, 395011:L:20170831, 399010:L:20170831, ...]      M         68         0              0                 5                  0                     01     2017-08-30                 0                     00     2017-09-04
3       45892  41385331             I5001    [I5013, I2728, Z950, E876, N183, ...]  992212::20170515                                                                  [890A32::20170515, 8945::20170515]      W         92         0              0                17                  0                     01     2017-05-15                 0                     00     2017-06-01
4       46427  41577513              E222       [Y579, E871, R400, R470, N40, ...]  99B712::20171114                                [891499::20171114, 0331::20171114, 5794::20171115, 889110::20171116]      M         82         0              0                13                  0                     11     2017-11-14                 0                     00     2017-11-27

In [5]:
if unmatched.shape[0] > 0:
    unmatched

In [6]:
revisions_update, diagnoses_update, procedures_update = group(revised_cases)
revisions_update[REVISION_DATE_COL] = '2022-12-31'

2022-11-09 16:05:55.585 | INFO     | src.revised_case_normalization.notebook_functions.group:group:78 - Grouping 126 cases ...

KeyError: "Key 'procedures' not found. If specifying a record_path, all elements of data should have the path."

In [ ]:
revisions_update

In [ ]:
update_db(revisions_update, diagnoses_update, procedures_update)