# Revised case normalization for Hirslanden Salem 2017

In [1]:
import pandas as pd
import sys
sys.path.insert(0, '/home/jovyan/work')

import os

from py.global_configs import *
from py.normalize import normalize

from src.service import bfs_cases_db_service as bfs_db

from src.utils.dataframe_utils import remove_duplicated_chops

/home/jovyan/work/src/models/BfsCase.py:5: SAWarning: On class 'BfsCase', Column object 'drg_cost_weight' named directly multiple times, only one will be used: drg_cost_weight, effective_cost_weight. Consider using orm.synonym instead
  class BfsCase(Base):

In [2]:

file_info = FileInfo(
        os.path.join(ROOT_DIR, 'raw_data/HI-Zurich.xlsx'),
        'Hirslanden Zurich',
        '2016',
        ['Änderungen_Hirslanden 2016'])

print(file_info)

FileInfo(path='/home/jovyan/work/src/revised_case_normalization/raw_data/HI-Zurich.xlsx', hospital_name_db='Hirslanden Zurich', year='2016', sheets=['Änderungen_Hirslanden 2016'])

In [3]:
cols_to_rename = dict(COLUMNS_TO_RENAME)
# Replace 'admno' with 'fall nummer'
cols_to_rename.pop('admno')
cols_to_rename['fall nummer'] = CASE_ID_COL

df_revised_case_d2d = normalize(file_info, 0)

2022-10-17 14:01:51.561 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 10: discarded ICDs after validation {'I50.01'}
2022-10-17 14:01:51.562 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 20: discarded ICDs after validation {'D68.4'}
2022-10-17 14:01:51.563 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 23: discarded ICDs after validation {'A41.9'}
2022-10-17 14:01:51.564 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 35: discarded ICDs after validation {'D68.22'}
2022-10-17 14:01:51.566 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 77: discarded ICDs after validation {''}
2022-10-17 14:01:51.567 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 84: discarded ICDs after validation {'D68.5'}
2022-10-17 14:01:51.570 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 0: discarded ICDs after validation {''}
2022-10-17 14:01:51.571 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 1: discarded ICDs after validation {''}
2022-10-17 14:01:51.571 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 2: discarded ICDs after validation {''}

Read 104 cases for Hirslanden Zurich 2016
TYPES:
case_id             string
patient_id          string
gender              string
age_years            int64
duration_of_stay     int64
pccl                 int64
drg                 string
old_pd              string
new_pd              string
bfs_code            string
added_icds          string
removed_icds        string
added_chops         string
removed_chops       string
dtype: object

2022-10-17 14:01:51.572 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 3: discarded ICDs after validation {''}
2022-10-17 14:01:51.573 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 4: discarded ICDs after validation {''}
2022-10-17 14:01:51.574 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 5: discarded ICDs after validation {''}
2022-10-17 14:01:51.575 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 6: discarded ICDs after validation {''}
2022-10-17 14:01:51.575 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 7: discarded ICDs after validation {''}
2022-10-17 14:01:51.576 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 8: discarded ICDs after validation {''}
2022-10-17 14:01:51.577 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 9: discarded ICDs after validation {''}
2022-10-17 14:01:51.578 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 12: discarded ICDs after validation {''}
2022-10-17 14:01:51.578 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 13: discarded ICDs after validation {''}
2022-10-17 14:01:51.579 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 14: discarded ICDs after validation {''}
2022-10-17 14:01:51.580 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 15: discarded ICDs after validation {''}
2022-10-17 14:01:51.580 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 16: discarded ICDs after validation {''}
2022-10-17 14:01:51.581 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 17: discarded ICDs after validation {''}
2022-10-17 14:01:51.582 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 18: discarded ICDs after validation {''}
2022-10-17 14:01:51.582 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 19: discarded ICDs after validation {''}
2022-10-17 14:01:51.582 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 21: discarded ICDs after validation {''}
2022-10-17 14:01:51.583 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 22: discarded ICDs after validation {''}
2022-10-17 14:01:51.584 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 23: discarded ICDs after validation {''}
2022-10-17 14:01:51.584 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 26: discarded ICDs after validation {''}
2022-10-17 14:01:51.585 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 27: discarded ICDs after validation {''}
2022-10-17 14:01:51.586 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 29: discarded ICDs after validation {''}
2022-10-17 14:01:51.586 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 30: discarded ICDs after validation {''}
2022-10-17 14:01:51.587 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 31: discarded ICDs after validation {''}
2022-10-17 14:01:51.587 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 33: discarded ICDs after validation {''}
2022-10-17 14:01:51.588 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 35: discarded ICDs after validation {''}
2022-10-17 14:01:51.589 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 36: discarded ICDs after validation {''}
2022-10-17 14:01:51.589 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 37: discarded ICDs after validation {''}
2022-10-17 14:01:51.590 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 38: discarded ICDs after validation {''}
2022-10-17 14:01:51.591 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 39: discarded ICDs after validation {''}
2022-10-17 14:01:51.592 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 40: discarded ICDs after validation {''}
2022-10-17 14:01:51.592 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 41: discarded ICDs after validation {''}
2022-10-17 14:01:51.593 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 42: discarded ICDs after validation {''}
2022-10-17 14:01:51.594 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 45: discarded ICDs after validation {''}
2022-10-17 14:01:51.595 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 46: discarded ICDs after validation {''}
2022-10-17 14:01:51.595 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 47: discarded ICDs after validation {''}
2022-10-17 14:01:51.596 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 48: discarded ICDs after validation {''}
2022-10-17 14:01:51.596 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 49: discarded ICDs after validation {''}
2022-10-17 14:01:51.597 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 53: discarded ICDs after validation {''}
2022-10-17 14:01:51.597 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 54: discarded ICDs after validation {''}
2022-10-17 14:01:51.598 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 55: discarded ICDs after validation {''}
2022-10-17 14:01:51.599 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 57: discarded ICDs after validation {''}
2022-10-17 14:01:51.600 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 58: discarded ICDs after validation {''}
2022-10-17 14:01:51.601 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 59: discarded ICDs after validation {''}
2022-10-17 14:01:51.601 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 60: discarded ICDs after validation {''}
2022-10-17 14:01:51.601 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 61: discarded ICDs after validation {''}
2022-10-17 14:01:51.602 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 62: discarded ICDs after validation {''}
2022-10-17 14:01:51.602 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 63: discarded ICDs after validation {''}
2022-10-17 14:01:51.603 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 64: discarded ICDs after validation {''}
2022-10-17 14:01:51.604 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 65: discarded ICDs after validation {''}
2022-10-17 14:01:51.605 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 66: discarded ICDs after validation {''}
2022-10-17 14:01:51.605 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 67: discarded ICDs after validation {''}
2022-10-17 14:01:51.606 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 68: discarded ICDs after validation {''}
2022-10-17 14:01:51.607 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 69: discarded ICDs after validation {''}
2022-10-17 14:01:51.607 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 70: discarded ICDs after validation {''}
2022-10-17 14:01:51.608 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 71: discarded ICDs after validation {''}
2022-10-17 14:01:51.609 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 74: discarded ICDs after validation {''}
2022-10-17 14:01:51.610 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 75: discarded ICDs after validation {''}
2022-10-17 14:01:51.610 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 76: discarded ICDs after validation {''}
2022-10-17 14:01:51.611 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 77: discarded ICDs after validation {''}
2022-10-17 14:01:51.611 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 78: discarded ICDs after validation {''}
2022-10-17 14:01:51.612 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 79: discarded ICDs after validation {''}
2022-10-17 14:01:51.613 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 80: discarded ICDs after validation {''}
2022-10-17 14:01:51.613 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 81: discarded ICDs after validation {''}
2022-10-17 14:01:51.614 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 82: discarded ICDs after validation {''}
2022-10-17 14:01:51.615 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 84: discarded ICDs after validation {''}
2022-10-17 14:01:51.615 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 85: discarded ICDs after validation {''}
2022-10-17 14:01:51.616 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 87: discarded ICDs after validation {''}
2022-10-17 14:01:51.616 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 88: discarded ICDs after validation {''}
2022-10-17 14:01:51.617 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 89: discarded ICDs after validation {''}
2022-10-17 14:01:51.617 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 91: discarded ICDs after validation {''}
2022-10-17 14:01:51.618 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 93: discarded ICDs after validation {''}
2022-10-17 14:01:51.619 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 95: discarded ICDs after validation {''}
2022-10-17 14:01:51.620 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 97: discarded ICDs after validation {''}
2022-10-17 14:01:51.620 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 98: discarded ICDs after validation {''}
2022-10-17 14:01:51.621 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 99: discarded ICDs after validation {''}
2022-10-17 14:01:51.621 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 100: discarded ICDs after validation {''}
2022-10-17 14:01:51.622 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 101: discarded ICDs after validation {''}
2022-10-17 14:01:51.623 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 102: discarded ICDs after validation {''}
2022-10-17 14:01:51.624 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 103: discarded ICDs after validation {''}
2022-10-17 14:01:51.626 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 0: discarded duplicated and invalid CHOP entries after validation {'863x10:R:20160107', '403x23:B:20160107', '009a26:R:20160107'}
2022-10-17 14:01:51.627 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 1: discarded duplicated and invalid CHOP entries after validation {'948x41::20160112', '99b713::20160105'}
2022-10-17 14:01:51.627 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 2: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.628 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 3: discarded duplicated and invalid CHOP entries after validation {'99b712::20160114'}
2022-10-17 14:01:51.629 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 4: discarded duplicated and invalid CHOP entries after validation {'99b711::20160128'}
2022-10-17 14:01:51.629 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 5: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.630 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 6: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.630 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 7: discarded duplicated and invalid CHOP entries after validation {'99b711::20160225'}
2022-10-17 14:01:51.631 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 8: discarded duplicated and invalid CHOP entries after validation {'99b713::20160121', '890a32::20160126', '009a13::20160121'}
2022-10-17 14:01:51.632 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 9: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.632 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 10: discarded duplicated and invalid CHOP entries after validation {'99b712::20160127', '361d11::20160127'}
2022-10-17 14:01:51.633 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 11: discarded duplicated and invalid CHOP entries after validation {'890a32::20160121'}
2022-10-17 14:01:51.633 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 12: discarded duplicated and invalid CHOP entries after validation {'99b711::20160120'}
2022-10-17 14:01:51.634 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 14: discarded duplicated and invalid CHOP entries after validation {'948x41::20160126'}
2022-10-17 14:01:51.635 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 15: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.635 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 16: discarded duplicated and invalid CHOP entries after validation {'009a13::20160304', '502a2a::20160304', '99b713::20160304'}
2022-10-17 14:01:51.636 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 17: discarded duplicated and invalid CHOP entries after validation {'99b711::20160318'}
2022-10-17 14:01:51.637 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 18: discarded duplicated and invalid CHOP entries after validation {'99b711::20160421'}
2022-10-17 14:01:51.637 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 19: discarded duplicated and invalid CHOP entries after validation {'99b713::20160320'}
2022-10-17 14:01:51.637 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 20: discarded duplicated and invalid CHOP entries after validation {'99b711::20160328', '544x12::20160329', '009a2a::20160329'}
2022-10-17 14:01:51.638 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 21: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.639 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 22: discarded duplicated and invalid CHOP entries after validation {'890a32::20160418', '009a14::20160415', '99b711::20160414'}
2022-10-17 14:01:51.640 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 23: discarded duplicated and invalid CHOP entries after validation {'99b711::20160424'}
2022-10-17 14:01:51.640 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 24: discarded duplicated and invalid CHOP entries after validation {'004c11::20160308'}
2022-10-17 14:01:51.641 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 25: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.642 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 26: discarded duplicated and invalid CHOP entries after validation {'009a13::20160425'}
2022-10-17 14:01:51.642 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 27: discarded duplicated and invalid CHOP entries after validation {'598x10:B:20160408', '99b711::20160408', '605x30::20160408', '403x24:B:20160408'}
2022-10-17 14:01:51.643 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 28: discarded duplicated and invalid CHOP entries after validation {'570x10::20160406'}
2022-10-17 14:01:51.644 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 29: discarded duplicated and invalid CHOP entries after validation {'377a23::20160519'}
2022-10-17 14:01:51.644 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 30: discarded duplicated and invalid CHOP entries after validation {'004a06::20160531'}
2022-10-17 14:01:51.645 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 31: discarded duplicated and invalid CHOP entries after validation {'939b::20160514', '99b713::20160514'}
2022-10-17 14:01:51.646 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 32: discarded duplicated and invalid CHOP entries after validation {'570x99::20160701'}
2022-10-17 14:01:51.646 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 33: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.647 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 34: discarded duplicated and invalid CHOP entries after validation {'948x40::20160607', '890a32::20160607'}
2022-10-17 14:01:51.647 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 35: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.648 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 36: discarded duplicated and invalid CHOP entries after validation {'99b711::20160705'}
2022-10-17 14:01:51.649 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 37: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.649 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 38: discarded duplicated and invalid CHOP entries after validation {'99b713::20160826'}
2022-10-17 14:01:51.650 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 39: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.651 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 40: discarded duplicated and invalid CHOP entries after validation {'99b713::20160916'}
2022-10-17 14:01:51.652 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 41: discarded duplicated and invalid CHOP entries after validation {'99b711::20160907'}
2022-10-17 14:01:51.652 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 42: discarded duplicated and invalid CHOP entries after validation {'99b712::20160629'}
2022-10-17 14:01:51.653 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 43: discarded duplicated and invalid CHOP entries after validation {'502a23::20160808', '99b711::20160808', '009a13::20160808'}
2022-10-17 14:01:51.653 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 44: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.654 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 45: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.655 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 46: discarded duplicated and invalid CHOP entries after validation {'544x12:R:20160907', '009a12::20160907'}
2022-10-17 14:01:51.655 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 47: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-17 14:01:51.656 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 48: discarded duplicated and invalid CHOP entries after validation {'009a14::20160922', '99b711::20160922', '403x23::20160928', '009a12::20160922'}
2022-10-17 14:01:51.656 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 49: discarded duplicated and invalid CHOP entries after validation {'863x10::20160714'}
2022-10-17 14:01:51.657 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 50: discarded duplicated and invalid CHOP entries after validation {'890a32::20160824', '403x23:B:20160808', '403x24:B:20160808', '99b711::20160807'}

In [4]:
df_revised_case_d2d

,case_id,patient_id,gender,age_years,duration_of_stay,pccl,drg,old_pd,new_pd,bfs_code,added_icds,removed_icds,added_chops,removed_chops
0,40822411,19CA20CD5E408064,M,86,12,3,M09A,C61,C61,M200,[F058],[],[],[]
1,40828212,010B949C1F25E5CA,M,73,11,3,B20A,D333,D333,M200,[E891],[],[],[]
2,40835992,8F5D8BEA91706191,M,57,28,3,I09D,M4787,M4787,M200,"[I982, N179]",[],[],[]
3,40836137,BF0089E1CBFF5DF6,M,75,5,3,M02B,N40,N40,M200,"[N183, E1172, N083, D860]",[],[],[]
4,40838008,AABE4CDA053DAE66,W,78,10,3,I47Z,M161,M161,M200,"[E611, I81]",[],[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,41108786,AFCE26A3C48249DE,M,68,4,2,G72B,K210,K210,M100,[F102],[],[],[]
100,41145363,946C45A5B6534021,M,85,4,3,M09B,C61,C61,M200,[N183],[],[],[]
101,41165859,DABE6EC817B1FC84,M,82,12,3,I09D,M4807,M4807,M200,[R31],[],[],[]
102,41176991,391DC257DDCFD2BA,W,74,16,3,H41B,C240,C240,M100,[L8925],[],[],[]
103,41215286,C03B413A955F57F5,W,65,11,3,G60B,C786,C786,M100,[N12],[],[],[]

# Match revised DtoD data with the bfs data from the database

In [5]:
# get the case_id from revised_case

revised_case_id = df_revised_case_d2d['case_id'].values
revised_case_id

array(['40822411', '40828212', '40835992', '40836137', '40838008',
       '40852905', '40858393', '40859453', '40860914', '40866702',
       '40867184', '40868298', '40870946', '40872342', '40874659',
       '40878418', '40883642', '40936154', '40971959', '40916919',
       '40920406', '40923263', '40953011', '40974465', '40922301',
       '40923605', '40927245', '40945685', '40948411', '40981304',
       '40981454', '40987673', '40988089', '40995934', '41014809',
       '41017435', '41020881', '41053612', '41083402', '41087350',
       '41094423', '41102256', '41034198', '41064506', '41070240',
       '41075015', '41107840', '41120077', '41129488', '41057598',
       '41060715', '41067573', '41068225', '41077147', '41089486',
       '41091471', '41101715', '41105583', '41132701', '41154269',
       '41171276', '41196442', '41211996', '41219083', '41230525',
       '40903007', '40907297', '40915498', '40937439', '40944820',
       '40959432', '40967233', '40973967', '40996051', '41007817',
       '41167697', '40889090', '40915299', '40981680', '41001751',
       '41112106', '41133497', '40873604', '40981332', '41019204',
       '41050225', '41065637', '41074177', '41077208', '41081188',
       '41087850', '40866938', '40872556', '40913836', '40925698',
       '40931704', '40987771', '41031914', '41086656', '41108786',
       '41145363', '41165859', '41176991', '41215286'], dtype=object)

In [6]:
revised_case_id_stripped = [case_id.lstrip('0') for case_id in revised_case_id]

In [7]:
# change the case_id the same format as bfs data e.g. '0041194601' 
# revised_case_id_pad0 = [case_id.zfill(10) for case_id in revised_case_id]
# revised_case_id_pad0[0]
# df_revised_case_d2d['case_id'] = revised_case_id_pad0

In [8]:
# match to the database
revised_case_db = bfs_db.get_bfs_cases_by_ids_no_pad0(revised_case_id_stripped)
revised_case_db.head()

,drg_cost_weight,aimedic_id,hospital_id,case_id,patient_id,age_years,age_days,gender,duration_of_stay,clinic_id,ventilation_hours,admission_weight,gestation_age,admission_date,admission_type,discharge_date,discharge_type,drg,adrg,pccl
0,1.477,375,1,40822411,19CA20CD5E408064,86,0,M,12,4,0,0,0,2016-01-07,01,2016-01-19,00,M09A,M09,3
0,3.301,520,1,40828212,010B949C1F25E5CA,73,0,M,11,4,24,0,0,2016-01-04,01,2016-01-15,00,B20A,B20,3
0,2.566,775,1,40835992,8F5D8BEA91706191,57,0,M,21,4,0,0,0,2016-01-19,01,2016-02-16,00,I09D,I09,3
0,0.768,780,1,40836137,BF0089E1CBFF5DF6,75,0,M,5,4,0,0,0,2016-01-14,01,2016-01-19,00,M02B,M02,3
0,1.690,880,1,40838008,AABE4CDA053DAE66,78,0,W,10,4,0,0,0,2016-01-26,01,2016-02-05,00,I47Z,I47,3

In [9]:
# create a new column for case_id_stripped with '0' for joining to the revised cases
revised_case_db['case_id_stripped']=  revised_case_db['case_id'].apply(lambda x: x.lstrip('0')) 
revised_case_db.head()

,drg_cost_weight,aimedic_id,hospital_id,case_id,patient_id,age_years,age_days,gender,duration_of_stay,clinic_id,...,admission_weight,gestation_age,admission_date,admission_type,discharge_date,discharge_type,drg,adrg,pccl,case_id_stripped
0,1.477,375,1,40822411,19CA20CD5E408064,86,0,M,12,4,...,0,0,2016-01-07,01,2016-01-19,00,M09A,M09,3,40822411
0,3.301,520,1,40828212,010B949C1F25E5CA,73,0,M,11,4,...,0,0,2016-01-04,01,2016-01-15,00,B20A,B20,3,40828212
0,2.566,775,1,40835992,8F5D8BEA91706191,57,0,M,21,4,...,0,0,2016-01-19,01,2016-02-16,00,I09D,I09,3,40835992
0,0.768,780,1,40836137,BF0089E1CBFF5DF6,75,0,M,5,4,...,0,0,2016-01-14,01,2016-01-19,00,M02B,M02,3,40836137
0,1.690,880,1,40838008,AABE4CDA053DAE66,78,0,W,10,4,...,0,0,2016-01-26,01,2016-02-05,00,I47Z,I47,3,40838008

In [10]:
df_revised_case_d2d['case_id_stripped']=  df_revised_case_d2d['case_id'].apply(lambda x: x.lstrip('0')) 
df_revised_case_d2d.head()

,case_id,patient_id,gender,age_years,duration_of_stay,pccl,drg,old_pd,new_pd,bfs_code,added_icds,removed_icds,added_chops,removed_chops,case_id_stripped
0,40822411,19CA20CD5E408064,M,86,12,3,M09A,C61,C61,M200,[F058],[],[],[],40822411
1,40828212,010B949C1F25E5CA,M,73,11,3,B20A,D333,D333,M200,[E891],[],[],[],40828212
2,40835992,8F5D8BEA91706191,M,57,28,3,I09D,M4787,M4787,M200,"[I982, N179]",[],[],[],40835992
3,40836137,BF0089E1CBFF5DF6,M,75,5,3,M02B,N40,N40,M200,"[N183, E1172, N083, D860]",[],[],[],40836137
4,40838008,AABE4CDA053DAE66,W,78,10,3,I47Z,M161,M161,M200,"[E611, I81]",[],[],[],40838008

# Forming the normalized dataframe: Merge the selected revised case data with the matched from bfs data
  If there are multiple cases were found based on case_id, patient_id will be used to match once more

In [11]:
# Check if there are multiple cases were found based on case_id, patient_id will be used to match once more
if revised_case_db.shape[0] <= len(revised_case_id):
    revised_case_d2d_subset = df_revised_case_d2d[COL_SUBSET_FROM_REVISED_CASES + ['case_id_stripped', 'gender', 'age_years', 'duration_of_stay', 'pccl', 'drg']]
    revised_case_normalized = revised_case_d2d_subset.merge(revised_case_db, how ='inner', on=['case_id_stripped', 'gender', 'age_years', 'duration_of_stay', 'pccl', 'drg'], suffixes=None)
    num_match_case_id = revised_case_normalized.shape[0]
else:
    revised_case_d2d_subset = df_revised_case_d2d[COL_SUBSET_FROM_REVISED_CASES + ['case_id_stripped', 'patient_id', 'gender', 'age_years', 'duration_of_stay', 'pccl', 'drg']]
    revised_case_normalized = revised_case_d2d_subset.merge(revised_case_db, how ='inner', on=['case_id_stripped', 'patient_id', 'gender', 'age_years', 'duration_of_stay', 'pccl', 'drg'])
    num_match_case_patient_id = revised_case_normalized.shape[0]
print(revised_case_normalized.shape)
revised_case_normalized.head()

(93, 28)

/tmp/ipykernel_11917/3233428173.py:4: FutureWarning: Passing 'suffixes' as a <class 'NoneType'>, is not supported and may give unexpected results. Provide 'suffixes' as a tuple instead. In the future a 'TypeError' will be raised.
  revised_case_normalized = revised_case_d2d_subset.merge(revised_case_db, how ='inner', on=['case_id_stripped', 'gender', 'age_years', 'duration_of_stay', 'pccl', 'drg'], suffixes=None)

,old_pd,new_pd,bfs_code,added_icds,removed_icds,added_chops,removed_chops,case_id_stripped,gender,age_years,...,age_days,clinic_id,ventilation_hours,admission_weight,gestation_age,admission_date,admission_type,discharge_date,discharge_type,adrg
0,C61,C61,M200,[F058],[],[],[],40822411,M,86,...,0,4,0,0,0,2016-01-07,01,2016-01-19,00,M09
1,D333,D333,M200,[E891],[],[],[],40828212,M,73,...,0,4,24,0,0,2016-01-04,01,2016-01-15,00,B20
2,N40,N40,M200,"[N183, E1172, N083, D860]",[],[],[],40836137,M,75,...,0,4,0,0,0,2016-01-14,01,2016-01-19,00,M02
3,M161,M161,M200,"[E611, I81]",[],[],[],40838008,W,78,...,0,4,0,0,0,2016-01-26,01,2016-02-05,00,I47
4,C796,C796,M300,[C795],[],[],[],40852905,W,47,...,0,5,0,0,0,2016-01-20,01,2016-01-22,00,N02

In [12]:
df_revised_case_normalized = revised_case_normalized[COLS_TO_SELECT]
df_revised_case_normalized.head()

,case_id,patient_id,gender,age_years,duration_of_stay,pccl,drg,old_pd,new_pd,bfs_code,added_icds,removed_icds,added_chops,removed_chops
0,40822411,19CA20CD5E408064,M,86,12,3,M09A,C61,C61,M200,[F058],[],[],[]
1,40828212,010B949C1F25E5CA,M,73,11,3,B20A,D333,D333,M200,[E891],[],[],[]
2,40836137,BF0089E1CBFF5DF6,M,75,5,3,M02B,N40,N40,M200,"[N183, E1172, N083, D860]",[],[],[]
3,40838008,AABE4CDA053DAE66,W,78,10,3,I47Z,M161,M161,M200,"[E611, I81]",[],[],[]
4,40852905,B827403A183AEE81,W,47,2,3,N02B,C796,C796,M300,[C795],[],[],[]

# Export the normalized revised cases with the neccessary columns to a csv file

In [13]:

hospital = file_info.hospital_name_db.replace(' ', '_') # replace spaces with '_' for the file name
hospital_year = f'{hospital}_{file_info.year}'

output_folder = os.path.join(ROOT_DIR, 'normalized_revision_data/')

if not os.path.exists(output_folder):
    os.mkdir(output_folder)

output_path = os.path.join(ROOT_DIR, 'normalized_revision_data/') + hospital_year + '.csv'

df_revised_case_normalized.to_csv(output_path)

# Report

A small summary of:
- how many cases could be matched in the DB, and based on which columns
- how many cases were “correctly” revised, in terms of upcoding (still need to do after the `grouper` is available for python)

In [14]:
if revised_case_db.shape[0] <= len(revised_case_id):
    print(f'Based on the columns "case_id", "gender, "age_years", "duration_of_stay", "pccl", "drg", there are {num_match_case_id} out of {len(revised_case_id)} revised cases from DtoD that can be matched with the bfs database data for {file_info.hospital_name_db} {file_info.year}' )
else:
    print(f'Based on the columns "case_id" and "Patient_id", "gender, "age_years", "duration_of_stay", "pccl", "drg", there are {num_match_case_patient_id} out of {len(revised_case_id)} revised cases from DtoD that can be matched with the bfs database data for {file_info.hospital_name_db} {file_info.year}' )

Based on the columns "case_id", "gender, "age_years", "duration_of_stay", "pccl", "drg", there are 93 out of 104 revised cases from DtoD that can be matched with the bfs database data for Hirslanden Zurich 2016

In [15]:
print('All the normalized revised cases are exported to here: {}'.format(output_path))

All the normalized revised cases are exported to here: /home/jovyan/work/src/revised_case_normalization/normalized_revision_data/Hirslanden_Zurich_2016.csv