# Revised case normalization for Winterthur 2017

This jupyter notebook is used to normalize the revised case from DtoD.

Before runing the notebook, raw_data folder need to added to the root directory

The raw data folder can be find here: https://aimedic.sharepoint.com/:f:/s/dev/Ejx_A1dg8gtPumFknOWOh0oBi6ofx9hctYiq3c-0gH9vYA?e=UmcgrS

Normalization:

-  Convert the column names to the name used in the Database
-  Delete cases which is empty in the follow columns VALIDATION_COLS: 'case_id', 'patient_id', 'gender', 'age_years', duration_of_stay',  'pccl',  'drg'
- choose neccessary columns COLS_TO_SELECT: case_id, patient_id, gender, age_years, duration_of_stay, pccl, drg, pd, bfs_code, added_icds, removed_icds, added_chops, removed_chops
- still need to do (TODO):    
    -  Check CHOP upper/lowercase
    -  Check whether the PD changed. If it did, new and old PD are stored together with added and removed ICDs, respectively
    -  Pad case IDs with 0s
    -  Write function to validate cases

In [1]:
import pandas as pd
import os
from dataclasses import dataclass, field
import sys
sys.path.insert(0, '/home/jovyan/work')
sys.path.insert(1, '/home/jovyan/work/src')
sys.path.insert(2, '/home/jovyan/work/src/service')

from service import bfs_cases_db_service as bfs_db

from py.global_configs import *
from py.normalize import normalize

/home/jovyan/work/src/models/BfsCase.py:5: SAWarning: On class 'BfsCase', Column object 'drg_cost_weight' named directly multiple times, only one will be used: drg_cost_weight, effective_cost_weight. Consider using orm.synonym instead
  class BfsCase(Base):

In [2]:
# check all the file name

FILES_TO_ANALYZE.keys()

dict_keys(['Hirslanden Salem 2017', 'Hirslanden Beau Site 2017', 'Hirslanden Linde 2017', 'Hirslanden Linde 2018', 'Hirslanden Salem 2018', 'Hirslanden Beau Site 2018', 'Winterthur 2017', 'Winterthur 2018', 'Winterthur 2019', 'Winterthur 2020'])

In [3]:
file = FILES_TO_ANALYZE['Winterthur 2017']
file

FileInfo(path='/home/jovyan/work/src/revised_case_normalization/raw_data/Winterthur.xlsx', hospital_name_db='KSW', year='2017', sheets=['Ã„nderungen _Winterthur_2017'])

In [4]:

df_revised_case_d2d = normalize(file, 0)

Read 218 cases for KSW 2017
TYPES:
case_id             string
patient_id          string
gender              string
age_years            int64
duration_of_stay     int64
pccl                 int64
drg                 string
pd                  string
bfs_code            string
added_icds          string
removed_icds        string
added_chops         string
removed_chops       string
dtype: object

In [5]:
df_revised_case_d2d.head()

,case_id,patient_id,gender,age_years,duration_of_stay,pccl,drg,pd,bfs_code,added_icds,removed_icds,added_chops,removed_chops
0,20066273027,D1B4E3C92520FC01,M,35,4,3,M60B,C61,M100,C787,<NA>,<NA>,<NA>
1,20093870027,13320B741B5845D4,M,84,17,3,I46C,S7210,M200,T840,<NA>,81525b:R:20170501,81525B:R:20170501
2,20158223027,BA43D16D9B8B472A,M,75,11,3,H01B,C787,M200,D684,<NA>,"502a27::20170803,009a13::20170803,99b711::2017...","502A27::20170803,009A13::20170803,99B711::2017..."
3,20219240027,7D29F200ABFD59CD,M,87,14,3,I46C,S7201,M100,B370,<NA>,<NA>,<NA>
4,20237303027,2BDCB561504F6656,W,83,7,3,I46C,S7201,M200,N182,<NA>,<NA>,<NA>

# match to the database

In [6]:
# get the case_id from revised_case

revised_case_id = df_revised_case_d2d['case_id'].values
revised_case_id

array(['20066273027', '20093870027', '20158223027', '20219240027',
       '20237303027', '20520053027', '20521883027', '20595506027',
       '20651153027', '20652950027', '20715770027', '20027270027',
       '20184413027', '20256623027', '20330843027', '20418443027',
       '20536136027', '20603690027', '20603840027', '20722103027',
       '20728766027', '20801606027', '20049053027', '20149040027',
       '20270936027', '20353373027', '20359340027', '20492120027',
       '20498453027', '20500583027', '20113853027', '20418260027',
       '20712080027', '20830463027', '20971223027', '21008423027',
       '20549333027', '20560670027', '20574206027', '20629073027',
       '20716973027', '20863823027', '20906963027', '20912420027',
       '20919833027', '20975933027', '20992130027', '20999783027',
       '21034103027', '21050840027', '21121763027', '21213383027',
       '21246380027', '21261323027', '21768383027', '21976340027',
       '21977336027', '21086843027', '21089240027', '21117230027',
       '21128606027', '21173210027', '21185513027', '21192113027',
       '21194273027', '21962093027', '21088643027', '21250820027',
       '21449450027', '21919820027', '21305240027', '21332330027',
       '21434453027', '21443033027', '21588500027', '21627140027',
       '21697490027', '21782303027', '21809333027', '21825113027',
       '21197420027', '21514883027', '21516623027', '21524636027',
       '21650690027', '21651650027', '21731783027', '21767780027',
       '21897503027', '21921563027', '21945623027', '22042820027',
       '21372773027', '21601313027', '21976040027', '22040306027',
       '22062173027', '21084266027', '21306293027', '21352913027',
       '21395996027', '21397223027', '21523703027', '21597023027',
       '21609653027', '21762590027', '21839003027', '21924353027',
       '21999593027', '21978050027', '22100513027', '21441563027',
       '21445313027', '21804890027', '21808463027', '21959450027',
       '21991430027', '22142990027', '22164020027', '22342733027',
       '21659213027', '22124183027', '22129106027', '22157090027',
       '22193870027', '22194113027', '22205996027', '22222793027',
       '22294463027', '22362050027', '22392380027', '22221740027',
       '22385810027', '22457210027', '22466390027', '22473836027',
       '22478930027', '22503920027', '22512893027', '22519406027',
       '22525166027', '22533803027', '22538606027', '22569473027',
       '22579730027', '22593860027', '22607243027', '22612880027',
       '22652996027', '22656743027', '22701950027', '22704950027',
       '22712336027', '22724570027', '22803266027', '22868993027',
       '22870223027', '22880066027', '22886570027', '22913396027',
       '22951223027', '22952810027', '22958450027', '22963043027',
       '20056370027', '20137043027', '20197613027', '20354720027',
       '20400206027', '20401220027', '22910660027', '22916033027',
       '22976240027', '4032073644', '6014011871', '20446880027',
       '20461400027', '20696003027', '20755763027', '20777570027',
       '20945150027', '22693940027', '21240890027', '21268190027',
       '21282896027', '21342896027', '21601673027', '21649793027',
       '21712640027', '20228393027', '20534423027', '21020480027',
       '21723560027', '21767750027', '21884543027', '22120883027',
       '22125506027', '22185080027', '20150666027', '21179096027',
       '21457940027', '22089383027', '22293083027', '22299863027',
       '20656580027', '21422693027', '21484283027', '21681566027',
       '21705350027', '22065080027', '22217903027', '22468883027',
       '20745680027', '21190583027', '21305870027', '22510853027',
       '22881800027', '9003011264'], dtype=object)

In [7]:
# match to the database
revised_case_db = bfs_db.get_bfs_cases_by_ids(revised_case_id)
revised_case_db.head()

,drg_cost_weight,aimedic_id,hospital_id,case_id,patient_id,age_years,age_days,gender,duration_of_stay,clinic_id,ventilation_hours,admission_weight,gestation_age,admission_date,admission_type,discharge_date,discharge_type,drg,adrg,pccl
0,1.127,105733,13,20027270027,52C61126FF3E328E,49,0,M,18,4,0,0,0,2017-05-02,01,2017-05-20,00,G07Z,G07,3
1,0.759,97561,13,20049053027,5F28DF79C45509D6,57,0,W,14,3,0,0,0,2017-08-14,01,2017-08-28,00,H62B,H62,3
2,0.506,110807,13,20056370027,B83FE2382CB15363,89,0,W,6,3,0,0,0,2017-05-09,01,2017-05-15,00,F72B,F72,2
3,0.668,93530,13,20066273027,D1B4E3C92520FC01,35,0,M,4,3,0,0,0,2017-10-14,01,2017-10-18,00,M60B,M60,3
4,1.677,97960,13,20093870027,13320B741B5845D4,84,0,M,17,4,0,0,0,2017-04-29,01,2017-05-16,00,I46C,I46,3

In [8]:
# 
print('There are {} out of {} revised cases from DtoD that are matched with the database for {} {}'.format(len(revised_case_db), len(revised_case_id), file.hospital_name_db, file.year))

There are 218 out of 218 revised cases from DtoD that are matched with the database for KSW 2017

In [9]:
# if we find the match cases, then we need to check if the case_id, gender, year....are match