# Revised case normalization for Hirslanden St. Anna 2018

In [1]:
import pandas as pd
import sys
sys.path.insert(0, '/home/jovyan/work')

import os

from py.global_configs import *
from py.normalize import normalize

from src.service import bfs_cases_db_service as bfs_db

from src.utils.dataframe_utils import remove_duplicated_chops

/home/jovyan/work/src/models/BfsCase.py:5: SAWarning: On class 'BfsCase', Column object 'drg_cost_weight' named directly multiple times, only one will be used: drg_cost_weight, effective_cost_weight. Consider using orm.synonym instead
  class BfsCase(Base):

In [2]:

file_info = FileInfo(
        os.path.join(ROOT_DIR, 'raw_data/HI_Aarau_Birshof_ST. Anna.xlsx'),
        'Hirslanden St. Anna',
        '2018',
        ['Änderungen_ST. Anna_2018'])
print(file_info)

FileInfo(path='/home/jovyan/work/src/revised_case_normalization/raw_data/HI_Aarau_Birshof_ST. Anna.xlsx', hospital_name_db='Hirslanden St. Anna', year='2018', sheets=['Änderungen_ST. Anna_2018'])

In [3]:
cols_to_rename = dict(COLUMNS_TO_RENAME)
# Replace 'admno' with 'fall nummer'
cols_to_rename.pop('admno')
cols_to_rename['fall nummer'] = CASE_ID_COL

df_revised_case_d2d = normalize(file_info, 0)

2022-10-18 10:36:27.117 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 2: discarded ICDs after validation {''}
2022-10-18 10:36:27.118 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 3: discarded ICDs after validation {''}
2022-10-18 10:36:27.118 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 5: discarded ICDs after validation {''}
2022-10-18 10:36:27.119 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 6: discarded ICDs after validation {''}
2022-10-18 10:36:27.120 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 7: discarded ICDs after validation {''}
2022-10-18 10:36:27.120 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 8: discarded ICDs after validation {''}
2022-10-18 10:36:27.121 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 9: discarded ICDs after validation {''}
2022-10-18 10:36:27.121 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 11: discarded ICDs after validation {''}
2022-10-18 10:36:27.122 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 12: discarded ICDs after validation {''}
2022-10-18 10:36:27.122 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 13: discarded ICDs after validation {''}
2022-10-18 10:36:27.123 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 14: discarded ICDs after validation {''}
2022-10-18 10:36:27.123 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 15: discarded ICDs after validation {''}
2022-10-18 10:36:27.124 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 16: discarded ICDs after validation {''}
2022-10-18 10:36:27.124 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 18: discarded ICDs after validation {''}
2022-10-18 10:36:27.125 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 22: discarded ICDs after validation {''}
2022-10-18 10:36:27.126 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 23: discarded ICDs after validation {''}
2022-10-18 10:36:27.126 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 24: discarded ICDs after validation {''}
2022-10-18 10:36:27.127 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 25: discarded ICDs after validation {''}
2022-10-18 10:36:27.128 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 26: discarded ICDs after validation {''}
2022-10-18 10:36:27.128 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 27: discarded ICDs after validation {''}
2022-10-18 10:36:27.129 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 28: discarded ICDs after validation {''}
2022-10-18 10:36:27.130 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 29: discarded ICDs after validation {''}
2022-10-18 10:36:27.130 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 30: discarded ICDs after validation {''}
2022-10-18 10:36:27.131 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 33: discarded ICDs after validation {''}
2022-10-18 10:36:27.131 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 34: discarded ICDs after validation {''}
2022-10-18 10:36:27.132 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 35: discarded ICDs after validation {''}
2022-10-18 10:36:27.132 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 36: discarded ICDs after validation {''}
2022-10-18 10:36:27.133 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 37: discarded ICDs after validation {''}
2022-10-18 10:36:27.134 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 38: discarded ICDs after validation {''}
2022-10-18 10:36:27.135 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 39: discarded ICDs after validation {''}
2022-10-18 10:36:27.136 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 41: discarded ICDs after validation {''}
2022-10-18 10:36:27.137 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 42: discarded ICDs after validation {''}
2022-10-18 10:36:27.138 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 44: discarded ICDs after validation {''}
2022-10-18 10:36:27.139 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 45: discarded ICDs after validation {''}
2022-10-18 10:36:27.139 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 46: discarded ICDs after validation {''}
2022-10-18 10:36:27.139 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 47: discarded ICDs after validation {''}
2022-10-18 10:36:27.140 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 48: discarded ICDs after validation {''}
2022-10-18 10:36:27.141 | DEBUG    | src.utils.dataframe_utils:_validate_icd_codes:56 - row 49: discarded ICDs after validation {''}
2022-10-18 10:36:27.142 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 0: discarded duplicated and invalid CHOP entries after validation {'948x40::20180202'}
2022-10-18 10:36:27.143 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 1: discarded duplicated and invalid CHOP entries after validation {'948x40::20180122'}
2022-10-18 10:36:27.143 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 2: discarded duplicated and invalid CHOP entries after validation {'99b812::20171225', '862a2e::20171225', '99221a::20171225'}
2022-10-18 10:36:27.144 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 3: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.144 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 4: discarded duplicated and invalid CHOP entries after validation {'862a2e::20180413'}
2022-10-18 10:36:27.145 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 5: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.145 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 6: discarded duplicated and invalid CHOP entries after validation {'948x40::20180212'}
2022-10-18 10:36:27.146 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 7: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.147 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 8: discarded duplicated and invalid CHOP entries after validation {'890a32::20180223', '867a9e:L:20180219'}
2022-10-18 10:36:27.148 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 9: discarded duplicated and invalid CHOP entries after validation {'890a11::20180314'}
2022-10-18 10:36:27.148 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 10: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.149 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 11: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.150 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 12: discarded duplicated and invalid CHOP entries after validation {'99b711::20180418'}
2022-10-18 10:36:27.151 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 13: discarded duplicated and invalid CHOP entries after validation {''}

Read 51 cases for Hirslanden St. Anna 2018
TYPES:
case_id             string
patient_id          string
gender              string
age_years            int64
duration_of_stay     int64
pccl                 int64
drg                 string
old_pd              string
new_pd              string
bfs_code            string
added_icds          string
removed_icds        string
added_chops         string
removed_chops       string
dtype: object

2022-10-18 10:36:27.152 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 14: discarded duplicated and invalid CHOP entries after validation {'009a14::20180404', '009a12::20180404', '403x23::20180404', '99b711::20180404', '544x11::20180404'}
2022-10-18 10:36:27.152 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 15: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.153 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 16: discarded duplicated and invalid CHOP entries after validation {'377a11:R:20180420', '377a13::20180420', '377b13::20180420', '377b11:R:20180420'}
2022-10-18 10:36:27.153 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 17: discarded duplicated and invalid CHOP entries after validation {'99b811::20180429', '948x40::20180429'}
2022-10-18 10:36:27.154 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 18: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.155 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 19: discarded duplicated and invalid CHOP entries after validation {'99b711::20180517', '009a13::20180517', '948x40::20180522', '403x26:R:20180517'}
2022-10-18 10:36:27.155 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 20: discarded duplicated and invalid CHOP entries after validation {'99b811::20180517'}
2022-10-18 10:36:27.156 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 21: discarded duplicated and invalid CHOP entries after validation {'009a13::20180517', '544x11::20180517', '403x29::20180517', '99b711::20180517', '543x19::20180517', '544x12::20180517'}
2022-10-18 10:36:27.156 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 22: discarded duplicated and invalid CHOP entries after validation {'99b711::20180524'}
2022-10-18 10:36:27.157 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 23: discarded duplicated and invalid CHOP entries after validation {'948x40::20180621'}
2022-10-18 10:36:27.157 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 24: discarded duplicated and invalid CHOP entries after validation {'009a13::20180607', '99b711::20180607', '403x29::20180607'}
2022-10-18 10:36:27.158 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 25: discarded duplicated and invalid CHOP entries after validation {'502a2c::20180611', '890a32::20180611', '544x12::20180611', '99b811::20180611', '403x23:B:20180611', '009a11::20180611'}
2022-10-18 10:36:27.159 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 26: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.159 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 27: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.160 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 28: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.160 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 29: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.161 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 30: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.162 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 31: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.162 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 32: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.163 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 33: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.163 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 34: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.164 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 35: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.164 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 36: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.165 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 37: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.166 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 38: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.166 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 39: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.167 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 40: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.168 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 41: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.168 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 42: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.169 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 43: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.169 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 44: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.170 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 45: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.170 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 46: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.171 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 47: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.172 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 48: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.172 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 49: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.173 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 50: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.175 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 0: discarded duplicated and invalid CHOP entries after validation {'948X40::20180202'}
2022-10-18 10:36:27.175 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 1: discarded duplicated and invalid CHOP entries after validation {'948X40::20180122'}
2022-10-18 10:36:27.176 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 2: discarded duplicated and invalid CHOP entries after validation {'862A2E::20171225', '99B812::20171225', '99221A::20171225'}
2022-10-18 10:36:27.177 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 3: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.177 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 4: discarded duplicated and invalid CHOP entries after validation {'862A2E::20180413'}
2022-10-18 10:36:27.178 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 5: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.178 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 6: discarded duplicated and invalid CHOP entries after validation {'948X40::20180212'}
2022-10-18 10:36:27.179 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 7: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.179 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 8: discarded duplicated and invalid CHOP entries after validation {'890A32::20180223', '867A9E:L:20180219'}
2022-10-18 10:36:27.180 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 9: discarded duplicated and invalid CHOP entries after validation {'890A11::20180314'}
2022-10-18 10:36:27.180 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 10: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.181 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 11: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.182 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 12: discarded duplicated and invalid CHOP entries after validation {'99B711::20180418'}
2022-10-18 10:36:27.183 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 13: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.183 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 14: discarded duplicated and invalid CHOP entries after validation {'009A12::20180404', '544X11::20180404', '403X23::20180404', '99B711::20180404', '009A14::20180404'}
2022-10-18 10:36:27.184 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 15: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.185 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 16: discarded duplicated and invalid CHOP entries after validation {'377A13::20180420', '377B13::20180420', '377B11:R:20180420', '377A11:R:20180420'}
2022-10-18 10:36:27.186 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 17: discarded duplicated and invalid CHOP entries after validation {'948X40::20180429', '99B811::20180429'}
2022-10-18 10:36:27.186 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 18: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.187 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 19: discarded duplicated and invalid CHOP entries after validation {'99B711::20180517', '948X40::20180522', '009A13::20180517', '403X26:R:20180517'}
2022-10-18 10:36:27.188 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 20: discarded duplicated and invalid CHOP entries after validation {'99B811::20180517'}
2022-10-18 10:36:27.188 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 21: discarded duplicated and invalid CHOP entries after validation {'544X12::20180517', '99B711::20180517', '543X19::20180517', '403X29::20180517', '544X11::20180517', '009A13::20180517'}
2022-10-18 10:36:27.189 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 22: discarded duplicated and invalid CHOP entries after validation {'99B711::20180524'}
2022-10-18 10:36:27.190 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 23: discarded duplicated and invalid CHOP entries after validation {'948X40::20180621'}
2022-10-18 10:36:27.190 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 24: discarded duplicated and invalid CHOP entries after validation {'009A13::20180607', '403X29::20180607', '99B711::20180607'}
2022-10-18 10:36:27.191 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 25: discarded duplicated and invalid CHOP entries after validation {'502A2C::20180611', '403X23:B:20180611', '544X12::20180611', '99B811::20180611', '009A11::20180611', '890A32::20180611'}
2022-10-18 10:36:27.192 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 26: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.192 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 27: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.193 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 28: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.193 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 29: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.194 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 30: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.195 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 31: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.195 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 32: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.196 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 33: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.197 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 34: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.198 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 35: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.198 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 36: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.199 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 37: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.200 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 38: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.200 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 39: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.201 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 40: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.202 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 41: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.202 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 42: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.203 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 43: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.204 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 44: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.204 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 45: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.205 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 46: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.206 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 47: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.207 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 48: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.207 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 49: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.208 | DEBUG    | src.utils.dataframe_utils:_validate_chop_codes:94 - row 50: discarded duplicated and invalid CHOP entries after validation {''}
2022-10-18 10:36:27.214 | DEBUG    | src.utils.dataframe_utils:_validate_pd_revised_sd:130 - in row 20, primary diagnosis was changed from T813 to M8668

In [4]:
df_revised_case_d2d

,case_id,patient_id,gender,age_years,duration_of_stay,pccl,drg,old_pd,new_pd,bfs_code,added_icds,removed_icds,added_chops,removed_chops
0,0009358410,EB395DA315D5B285,W,79,9,3,I46C,M169,M169,M200,[D62],[D648],[],[]
1,0009364697,6586D083924C0E99,W,68,16,3,I09C,M4806,M4806,M200,[E1191],[E1190],[],[]
2,0009366989,9FBF3AE4CEA4A950,M,27,16,3,I10C,M511,M511,M200,[B956],[],[],[]
3,0009371704,FDE409238A9BEC4F,M,65,13,3,F49C,I5001,I5001,M100,[N183],[],[],[]
4,0009375929,036F0863E37E3493,M,74,18,3,I27C,M4806,M4806,M200,[T846],[T844],[],[]
5,0009377457,B172FAC0D995D8A0,M,77,5,3,F62C,I5000,I5000,M100,"[K746, E870]",[],[],[]
6,0009381325,E3D0603E52140F32,W,55,15,3,E65B,J4410,J4410,M100,[J9610],[],[],[]
7,0009382082,4ED15568FB7BDE9E,M,82,8,3,E77E,J100,J100,M100,[E870],[],[],[]
8,0009384055,44197C8BC8569771,W,87,14,3,X06B,S8180,S8180,M200,[E871],[],[],[]
9,0009391002,8BD23E59AF760596,M,64,14,3,E77E,J128,J128,M100,[C9000],[],[],[]
10,0009392987,9EC05BADE92DD9DA,W,84,6,3,F73B,I952,I952,M100,"[I5014, J91]",[I5019],[],[]
11,0009394460,5BA4EADB25E2A8F3,M,56,6,3,J64C,A46,A46,M100,[I420],[],[],[]
12,0009394697,473E5E7C62FF006B,M,66,16,3,F34D,I723,I723,M200,"[E1191, N184]",[],[],[]
13,0009398985,4F59207EAD4B7645,M,87,15,3,I46C,S7204,S7204,M200,[N184],[],[],[]
14,0009399423,7B5A949774629FBC,W,81,8,3,G17Z,D012,D012,M200,"[E870, N183]",[],[],[]
15,0009402078,FE278AF26ECBCA7D,W,74,12,3,R61D,D467,D467,M100,[N183],[],[],[]
16,0009403476,E21BA5390CF3E1B6,M,76,4,3,F18B,T821,T821,M100,[N183],[],[],[]
17,0009409623,D12521E1C91607CA,M,85,8,3,I08D,S722,S722,M200,[D62],[D649],[990410],[]
18,0009410191,9C7D6310BAEC13C2,M,88,4,3,F71B,I489,I489,M100,[I429],[],[],[]
19,0009413115,A0332A739F771653,M,71,8,3,E01B,C341,C341,M200,[E1191],[E1190],[],[]
20,0009415487,22D3BAB3A7F94551,M,86,6,0,X06B,M8668,M8668,M200,[B956],[],[],[]
21,0009415740,4DA251A90E85300A,M,65,7,3,G18B,C181,C181,M200,[E1191],[E1190],[],[]
22,0009417723,E33A20FE08A721D0,M,51,7,3,F24E,I211,I211,M100,[I418],[],[],[]
23,0009418254,DCC8423814ABB39F,W,80,6,3,I46C,M169,M169,M200,[N182],[],[],[]
24,0009419360,5ED4CCBE338BC9C9,M,27,7,3,G18B,C184,C184,M200,[K567],[],[],[]
25,0009420462,9FB44506CB8A9FA4,W,56,9,3,N01B,C56,C56,M300,[D62],[],[],[]
26,9474338,ABDC07D2E5C7BBE4,W,88,4,3,L63D,N390,N390,M100,"[D619, C787, C792, C782]",[],[],[]
27,9474683,9F0DF3C4339A99DF,W,75,12,3,I08C,M9682,M9682,M200,"[M6585, G802]",[],[],[]
28,9475859,2FB3AEA2C8F01F86,M,58,6,3,R61D,C830,C830,M100,[L97],[],[],[]
29,9481220,B2EF1CA7B2A99134,M,88,5,3,I08D,S7210,S7210,M100,[F059],[],[],[]
30,9481953,DBE93EAC3AE419F5,W,70,6,3,I09D,M4786,M4786,M200,[F132],[],[],[]
31,9488156,D09E2D5677CCD518,M,84,5,3,E64C,I260,I260,M100,"[F009, G309, F051]",[F03],[],[]
32,9423361,07FF26F7B776991B,M,78,6,3,G48C,K264,K264,M100,[D62],[D648],[],[]
33,9425905,7520684D182EDB52,W,74,5,3,F75D,I422,I422,M100,[I513],[],[],[]
34,9428926,CC9316ED861CF829,M,85,9,3,E77C,A481,A481,M100,[N183],[],[],[]
35,9430324,CE5D8717F03B0D9A,M,79,8,3,I09C,M4786,M4786,M200,"[E854, I431, I484]",[],[],[]
36,9430945,57431D9E0421FB43,W,73,5,3,E71B,C343,C343,M100,[R650],[],[],[]
37,9433155,22C9BBA7B4A0A473,W,77,16,3,G21B,K565,K565,M200,[E870],[],[],[]
38,9433593,8CB9E64487466279,M,71,4,3,L63D,N390,N390,M100,"[G114, G8249]",[],[],[]
39,9434874,6D3A3A3C04AAB3C9,W,78,6,3,L63D,N390,N390,M100,[I652],[],[],[]
40,9436804,BFCF966EBB6145E6,W,87,5,3,I08D,S7211,S7211,M200,[E1191],[E1190],[],[]
41,0009443438,501E6414F736C132,M,52,5,3,E05C,J869,J869,M200,[J9600],[],[],[]
42,0009445581,449EECE2C1A4397D,W,55,9,3,G21B,K565,K565,M200,"[K358, K550]",[],[],[]
43,0009446567,696E6FDE1B291370,W,90,11,3,E69C,J208,J208,M100,[N183],[N182],[],[]
44,0009447736,56B952F2064DCF1E,M,64,18,3,R01D,C862,C862,M200,[K658],[],[],[]
45,0009453317,B1EE22199F1E19CA,M,79,15,3,E65C,J4419,J4419,M100,"[N183, J9600]",[],[],[]
46,0009456491,710F57AC1F5C5980,W,70,4,3,E64C,I269,I269,M100,[D6809],[],[],[]
47,0009457729,B215C731DBD0744F,W,61,9,3,T60E,A4151,A4151,M100,[J9600],[],[],[]
48,0009458248,6B8BC10810390D1C,M,59,16,3,I09D,M4647,M4647,M200,[T842],[],[],[]
49,0009464585,5F6B8124186E2846,M,66,7,3,I46C,M169,M169,M200,[D62],[],[],[]
50,0009465161,E1C62119A318DD23,M,73,6,3,E69C,J459,J459,M100,[E1191],[E1190],[],[]

# Match revised DtoD data with the bfs data from the database

In [5]:
# get the case_id from revised_case

revised_case_id = df_revised_case_d2d['case_id'].values
revised_case_id

array(['0009358410', '0009364697', '0009366989', '0009371704',
       '0009375929', '0009377457', '0009381325', '0009382082',
       '0009384055', '0009391002', '0009392987', '0009394460',
       '0009394697', '0009398985', '0009399423', '0009402078',
       '0009403476', '0009409623', '0009410191', '0009413115',
       '0009415487', '0009415740', '0009417723', '0009418254',
       '0009419360', '0009420462', '9474338', '9474683', '9475859',
       '9481220', '9481953', '9488156', '9423361', '9425905', '9428926',
       '9430324', '9430945', '9433155', '9433593', '9434874', '9436804',
       '0009443438', '0009445581', '0009446567', '0009447736',
       '0009453317', '0009456491', '0009457729', '0009458248',
       '0009464585', '0009465161'], dtype=object)

In [6]:
revised_case_id_stripped = [case_id.lstrip('0') for case_id in revised_case_id]

### Check if there are duplicated case_ids in the revised cases after stripping the 0 in front, if yes, delete duplicated cases

In [7]:

revised_case_id_stripped_set = set(revised_case_id_stripped)
if len(revised_case_id_stripped) > len(revised_case_id_stripped_set):
    print('There are duplicated case_ids in the revised cases.' )
else:
    print('There are no duplicated case_ids in the revised cases.' )

There are no duplicated case_ids in the revised cases.

In [8]:
# match to the database and retrieve data from database using revised
revised_case_db = bfs_db.get_bfs_cases_by_ids_no_pad0(list(revised_case_id_stripped_set))
revised_case_db.head()

,drg_cost_weight,aimedic_id,hospital_id,case_id,patient_id,age_years,age_days,gender,duration_of_stay,clinic_id,ventilation_hours,admission_weight,gestation_age,admission_date,admission_type,discharge_date,discharge_type,drg,adrg,pccl
0,1.132,145553,4,0009428926,CC9316ED861CF829,85,0,M,9,3,0,0,0,2018-06-26,01,2018-07-05,00,E77C,E77,3
0,1.781,144172,4,0009415740,4DA251A90E85300A,65,0,M,7,4,0,0,0,2018-05-17,01,2018-05-24,00,G18B,G18,3
0,0.707,148653,4,0009456491,710F57AC1F5C5980,70,0,W,4,3,0,0,0,2018-09-21,01,2018-09-25,00,E64C,E64,3
0,0.571,142190,4,0009394460,5BA4EADB25E2A8F3,56,0,M,6,3,0,0,0,2018-03-17,01,2018-03-23,00,J64C,J64,3
0,0.858,140323,4,0009377457,B172FAC0D995D8A0,77,0,M,5,3,0,0,0,2018-01-27,01,2018-02-01,00,F62C,F62,3

In [9]:
# create a new column for case_id_stripped with '0' for joining to the revised cases
revised_case_db['case_id_stripped']=  revised_case_db['case_id'].apply(lambda x: x.lstrip('0')) 
revised_case_db.head()

,drg_cost_weight,aimedic_id,hospital_id,case_id,patient_id,age_years,age_days,gender,duration_of_stay,clinic_id,...,admission_weight,gestation_age,admission_date,admission_type,discharge_date,discharge_type,drg,adrg,pccl,case_id_stripped
0,1.132,145553,4,0009428926,CC9316ED861CF829,85,0,M,9,3,...,0,0,2018-06-26,01,2018-07-05,00,E77C,E77,3,9428926
0,1.781,144172,4,0009415740,4DA251A90E85300A,65,0,M,7,4,...,0,0,2018-05-17,01,2018-05-24,00,G18B,G18,3,9415740
0,0.707,148653,4,0009456491,710F57AC1F5C5980,70,0,W,4,3,...,0,0,2018-09-21,01,2018-09-25,00,E64C,E64,3,9456491
0,0.571,142190,4,0009394460,5BA4EADB25E2A8F3,56,0,M,6,3,...,0,0,2018-03-17,01,2018-03-23,00,J64C,J64,3,9394460
0,0.858,140323,4,0009377457,B172FAC0D995D8A0,77,0,M,5,3,...,0,0,2018-01-27,01,2018-02-01,00,F62C,F62,3,9377457

In [10]:
# create a new column for case_id_stripped with '0' for joining to the revised cases
revised_case_db['case_id_stripped']=  revised_case_db['case_id'].apply(lambda x: x.lstrip('0')) 
revised_case_db.head()
print(revised_case_db.shape)

(51, 21)

In [11]:
# create a new column for case_id_stripped with '0' for joining to cases from database

df_revised_case_d2d['case_id_stripped']=  df_revised_case_d2d['case_id'].apply(lambda x: x.lstrip('0')) 
df_revised_case_d2d.head()
print(df_revised_case_d2d.shape)

(51, 15)

In [12]:
# delete duplicated cases in the revised cases

df_revised_case_d2d['case_id_stripped'].apply(tuple) # make sure the drop_duplicates works

df_revised_case_d2d.drop_duplicates(subset=['case_id_stripped'], keep='last', inplace=True)
assert len(revised_case_id_stripped) == df_revised_case_d2d.shape[0] # make sure all cases are deleted

# Forming the normalized dataframe: Merge the selected revised case data with the matched from bfs data
  If there are multiple cases were found based on case_id, patient_id will be used to match once more

In [13]:
# Check if there are multiple cases were found based on case_id, patient_id will be used to match once more
if revised_case_db.shape[0] <= len(revised_case_id):
    revised_case_d2d_subset = df_revised_case_d2d[COL_SUBSET_FROM_REVISED_CASES + ['case_id_stripped', 'gender', 'age_years', 'duration_of_stay', 'pccl', 'drg']]
    revised_case_normalized = revised_case_db.merge(revised_case_d2d_subset, how ='left', on=['case_id_stripped', 'gender', 'age_years', 'duration_of_stay', 'pccl', 'drg'])
    num_match_case_id = revised_case_normalized.shape[0]
else:
    revised_case_d2d_subset = df_revised_case_d2d[COL_SUBSET_FROM_REVISED_CASES + ['case_id_stripped', 'patient_id', 'gender', 'age_years', 'duration_of_stay', 'pccl', 'drg']]
    revised_case_normalized = revised_case_db.merge(revised_case_d2d_subset, how ='left', on=['case_id_stripped', 'gender', 'age_years', 'duration_of_stay', 'pccl', 'drg'])
    num_match_case_patient_id = revised_case_normalized.shape[0]
print(revised_case_normalized.shape)
revised_case_normalized.head()

(51, 28)

,drg_cost_weight,aimedic_id,hospital_id,case_id,patient_id,age_years,age_days,gender,duration_of_stay,clinic_id,...,adrg,pccl,case_id_stripped,old_pd,new_pd,bfs_code,added_icds,removed_icds,added_chops,removed_chops
0,1.132,145553,4,0009428926,CC9316ED861CF829,85,0,M,9,3,...,E77,3,9428926,A481,A481,M100,[N183],[],[],[]
1,1.781,144172,4,0009415740,4DA251A90E85300A,65,0,M,7,4,...,G18,3,9415740,C181,C181,M200,[E1191],[E1190],[],[]
2,0.707,148653,4,0009456491,710F57AC1F5C5980,70,0,W,4,3,...,E64,3,9456491,I269,I269,M100,[D6809],[],[],[]
3,0.571,142190,4,0009394460,5BA4EADB25E2A8F3,56,0,M,6,3,...,J64,3,9394460,A46,A46,M100,[I420],[],[],[]
4,0.858,140323,4,0009377457,B172FAC0D995D8A0,77,0,M,5,3,...,F62,3,9377457,I5000,I5000,M100,"[K746, E870]",[],[],[]

In [14]:
# Choose column to export to a csv file
df_revised_case_normalized = revised_case_normalized[COLS_TO_OUTPUT]
assert len(df_revised_case_normalized.columns) == len(COLS_TO_OUTPUT)
df_revised_case_normalized.head()

,aimedic_id,case_id,patient_id,gender,age_years,duration_of_stay,pccl,drg,old_pd,new_pd,bfs_code,added_icds,removed_icds,added_chops,removed_chops
0,145553,0009428926,CC9316ED861CF829,M,85,9,3,E77C,A481,A481,M100,[N183],[],[],[]
1,144172,0009415740,4DA251A90E85300A,M,65,7,3,G18B,C181,C181,M200,[E1191],[E1190],[],[]
2,148653,0009456491,710F57AC1F5C5980,W,70,4,3,E64C,I269,I269,M100,[D6809],[],[],[]
3,142190,0009394460,5BA4EADB25E2A8F3,M,56,6,3,J64C,A46,A46,M100,[I420],[],[],[]
4,140323,0009377457,B172FAC0D995D8A0,M,77,5,3,F62C,I5000,I5000,M100,"[K746, E870]",[],[],[]

# Export the normalized revised cases with the neccessary columns to a csv file

In [15]:

hospital = file_info.hospital_name_db.replace(' ', '_') # replace spaces with '_' for the file name
hospital_year = f'{hospital}_{file_info.year}'

output_folder = os.path.join(ROOT_DIR, 'normalized_revision_data/')

if not os.path.exists(output_folder):
    os.mkdir(output_folder)

output_path = os.path.join(ROOT_DIR, 'normalized_revision_data/') + hospital_year + '.csv'

df_revised_case_normalized.to_csv(output_path)

# Report

A small summary of:
- how many cases could be matched in the DB, and based on which columns
- how many cases were “correctly” revised, in terms of upcoding (still need to do after the `grouper` is available for python)

In [16]:
if revised_case_db.shape[0] <= len(revised_case_id):
    print(f'Based on the columns "case_id", "gender, "age_years", "duration_of_stay", "pccl", "drg", there are {num_match_case_id} out of {len(revised_case_id)} revised cases from DtoD that can be matched with the bfs database data for {file_info.hospital_name_db} {file_info.year}' )
else:
    print(f'Based on the columns "case_id" and "Patient_id", "gender, "age_years", "duration_of_stay", "pccl", "drg", there are {num_match_case_patient_id} out of {len(revised_case_id)} revised cases from DtoD that can be matched with the bfs database data for {file_info.hospital_name_db} {file_info.year}' )

Based on the columns "case_id", "gender, "age_years", "duration_of_stay", "pccl", "drg", there are 51 out of 51 revised cases from DtoD that can be matched with the bfs database data for Hirslanden St. Anna 2018

In [17]:
print('All the normalized revised cases are exported to here: {}'.format(output_path))

All the normalized revised cases are exported to here: /home/jovyan/work/src/revised_case_normalization/normalized_revision_data/Hirslanden_St._Anna_2018.csv